name: Build & Publish API snapshot to data.covidactnow.org

#######################################################################################
###
### YOU DON'T NEED TO MODIFY THIS FILE TO KICK OFF A SNAPSHOT FROM YOUR BRANCH ANYMORE.
###
### See: https://github.com/covid-projections/covid-data-model/#api-snapshots
###
#######################################################################################

on:
  workflow_dispatch:
    inputs:
      sentry_environment:
        description: 'Sentry environment of build. Should be "production" on main build and "staging" for other branches.'
        required: true

env:
  # TODO: This may no longer be used for anything anymore. Remove?
  COVID_DATA_PUBLIC_REF: 'main'

  # S3 Bucket (used by s3-sync-action tasks) to store final API snapshot.
  AWS_S3_BUCKET: 'data.covidactnow.org'

  # Use plotting by default on CI
  PYSEIR_PLOT_RESULTS: 'True'

  # The snapshot ID that identifies all of the API artifacts we're generating and ends
  # up in the final /snapshot/{id}/ URL.
  SNAPSHOT_ID: ${{github.run_number}}

  # Used by execute-model (for now) to optimize parallelization on self-hosted
  # runner.
  COVID_MODEL_CORES: 96

  # Used by python code that reports errors to sentry.
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

  # Sets the sentry environment, controlling how alerts are reported.
  SENTRY_ENVIRONMENT: ${{ github.event.inputs.sentry_environment }}

  # use a webhook to write to slack channel dev-alerts for QA
  SLACK_DEV_ALERTS_WEBHOOK: ${{ secrets.SLACK_DEV_ALERTS_WEBHOOK }}

  # Setting openblas threading to one to speed up numpy in multiprocessing.
  OPENBLAS_NUM_THREADS: 1

jobs:
  build-and-publish-snapshot:
    runs-on: self-hosted
    steps:
    - name: Parse covid data model branch name and set env variable
      run: |
        echo "COVID_DATA_MODEL_REF=${GITHUB_REF##*/}" >> $GITHUB_ENV
    - name: Checkout covid-data-model (${{ env.COVID_DATA_MODEL_REF }})
      uses: actions/checkout@v2
      with:
        repository: covid-projections/covid-data-model
        path: covid-data-model
        lfs: true
        ref: '${{env.COVID_DATA_MODEL_REF}}'
    - name: Checkout covid-data-public (${{ env.COVID_DATA_PUBLIC_REF }})
      uses: actions/checkout@v2
      with:
        repository: covid-projections/covid-data-public
        path: covid-data-public
        lfs: true
        ref: '${{env.COVID_DATA_PUBLIC_REF}}'

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7.6'
        architecture: 'x64'

    - name: Cache Pip
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-

    - name: Install Dependencies
      working-directory: ./covid-data-model
      run: pip install -r requirements.txt

    - name: Pull git lfs
      working-directory: ./covid-data-model
      run: git lfs pull

    - name: Build Model Results (run.sh .. .. execute_model)
      run: |
        ./covid-data-model/run.py utils download-model-artifact --github-token ${{ secrets.CAN_ROBOT_PERSONAL_ACCESS_TOKEN }} 2827

    - name: Build API (run.sh .. .. execute_api)
      run: |
        ./covid-data-model/run.py api generate-api-v2 --fips 31049 api-results-2827